const data: StarWarsRequest = {
  count: 3,
  next: null,
  previous: null,
  detail: null,
  results: [
    {
      name: 'Owen Lars',
      height: '178',
      mass: '120',
      hair_color: 'brown, grey',
      skin_color: 'light',
      eye_color: 'blue',
      birth_year: '52BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: [],
      starships: [],
      created: '2014-12-10T15:52:14.024000Z',
      edited: '2014-12-20T21:17:50.317000Z',
      url: 'https://swapi.dev/api/people/6/',
      climate: '',
      diameter: '',
      gravity: '',
      orbital_period: '',
      population: '',
      residents: [],
      rotation_period: '',
      surface_water: '',
      terrain: '',
      characters: [],
      director: '',
      episode_id: 0,
      opening_crawl: '',
      planets: [],
      producer: '',
      release_date: '',
      title: '',
      average_height: '',
      average_lifespan: '',
      classification: '',
      designation: '',
      eye_colors: '',
      hair_colors: '',
      language: '',
      people: [],
      skin_colors: '',
      cargo_capacity: '',
      consumables: '',
      cost_in_credits: '',
      crew: '',
      length: '',
      manufacturer: '',
      max_atmosphering_speed: '',
      model: '',
      passengers: '',
      pilots: [],
      vehicle_class: '',
      MGLT: '',
      hyperdrive_rating: '',
      starship_class: '',
      planetName: '',
    },
    {
      name: 'Beru Whitesun lars',
      height: '165',
      mass: '75',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'blue',
      birth_year: '47BBY',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: [],
      starships: [],
      created: '2014-12-10T15:53:41.121000Z',
      edited: '2014-12-20T21:17:50.319000Z',
      url: 'https://swapi.dev/api/people/7/',
      climate: '',
      diameter: '',
      gravity: '',
      orbital_period: '',
      population: '',
      residents: [],
      rotation_period: '',
      surface_water: '',
      terrain: '',
      characters: [],
      director: '',
      episode_id: 0,
      opening_crawl: '',
      planets: [],
      producer: '',
      release_date: '',
      title: '',
      average_height: '',
      average_lifespan: '',
      classification: '',
      designation: '',
      eye_colors: '',
      hair_colors: '',
      language: '',
      people: [],
      skin_colors: '',
      cargo_capacity: '',
      consumables: '',
      cost_in_credits: '',
      crew: '',
      length: '',
      manufacturer: '',
      max_atmosphering_speed: '',
      model: '',
      passengers: '',
      pilots: [],
      vehicle_class: '',
      MGLT: '',
      hyperdrive_rating: '',
      starship_class: '',
      planetName: '',
    },
    {
      name: 'Cliegg Lars',
      height: '183',
      mass: 'unknown',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '82BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: ['https://swapi.dev/api/films/5/'],
      species: [],
      vehicles: [],
      starships: [],
      created: '2014-12-20T15:59:03.958000Z',
      edited: '2014-12-20T21:17:50.451000Z',
      url: 'https://swapi.dev/api/people/62/',
      climate: '',
      diameter: '',
      gravity: '',
      orbital_period: '',
      population: '',
      residents: [],
      rotation_period: '',
      surface_water: '',
      terrain: '',
      characters: [],
      director: '',
      episode_id: 0,
      opening_crawl: '',
      planets: [],
      producer: '',
      release_date: '',
      title: '',
      average_height: '',
      average_lifespan: '',
      classification: '',
      designation: '',
      eye_colors: '',
      hair_colors: '',
      language: '',
      people: [],
      skin_colors: '',
      cargo_capacity: '',
      consumables: '',
      cost_in_credits: '',
      crew: '',
      length: '',
      manufacturer: '',
      max_atmosphering_speed: '',
      model: '',
      passengers: '',
      pilots: [],
      vehicle_class: '',
      MGLT: '',
      hyperdrive_rating: '',
      starship_class: '',
      planetName: '',
    },
  ],
};

import { render, screen } from '@testing-library/react';
import { it, expect, describe } from 'vitest';
import CardList from '../components/CardList/CardList';
import { StarWarsRequest } from '../types/types';
import '@testing-library/jest-dom/vitest';

describe('CardList', () => {
  it('should render correct name', () => {
    render(<CardList data={data} setData={() => {}} selectedType={null} />);
    const response = screen.getByText(data.results[0].name);
    expect(response).toHaveTextContent(data.results[0].name);
  });
});

describe('CardList', () => {
  it('should render correct count', () => {
    render(<CardList data={data} setData={() => {}} selectedType={null} />);
    const cards = screen.getAllByRole('card');
    expect(cards).toHaveLength(data.count);
  });
});

describe('CardList', () => {
  it('should render Not found', () => {
    data.count = 0;
    render(<CardList data={data} setData={() => {}} selectedType={null} />);
    const notFound = screen.getByText(/not found/i);
    expect(notFound).toBeInTheDocument();
  });
});
